name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged
    
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}